/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    guidelines: Guideline;
    pguide: Pguide;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'guidelines' | 'pguide';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    guidelines: GuidelinesSelect<false> | GuidelinesSelect<true>;
    pguide: PguideSelect<false> | PguideSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guidelines".
 */
export interface Guideline {
  id: string;
  title: string;
  /**
   * Auto-generated from title, but can be edited manually
   */
  slug?: string | null;
  localeSummary?: {
    locale?: string | null;
    countryISO?: string | null;
    dialingCode?: number | null;
    countryCode?: number | null;
  };
  regulatoryRequirements?: {
    requirementsSelection?: ('noReg' | 'optReg' | 'mandReg') | null;
  };
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  localOperators?:
    | {
        operator?: string | null;
        mnc?: number | null;
        numericId?: boolean | null;
        alphaId?: boolean | null;
        shortCode?: boolean | null;
        comments?: string | null;
        id?: string | null;
      }[]
    | null;
  features?: {
    dedicatedShortcodes?: boolean | null;
    sharedShortcodes?: boolean | null;
    longnumbers?: boolean | null;
  };
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: string;
  name: string;
  folder?: (string | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: string | FolderInterface;
        }
      | {
          relationTo?: 'guidelines';
          value: string | Guideline;
        }
      | {
          relationTo?: 'pguide';
          value: string | Pguide;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: ('guidelines' | 'pguide')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pguide".
 */
export interface Pguide {
  id: string;
  title: string;
  /**
   * Auto-generated from title, but can be edited manually
   */
  slug?: string | null;
  meta_fields: {
    /**
     * The title to use for the SEO meta tag.
     */
    seo_title: string;
    /**
     * The description to use for the SEO meta tag.
     */
    seo_description: string;
    /**
     * The title to use for the Open Graph meta tag. If not provided, the seo_title will be used.
     */
    og_title?: string | null;
    /**
     * The description to use for the Open Graph meta tag. If not provided, the seo_description will be used.
     */
    og_description?: string | null;
    /**
     * The image to use for the Open Graph image. If not provided, a default image will be used.
     */
    og_image?: (string | null) | Media;
  };
  internal_search: {
    /**
     * The title to use to display internal search results.
     */
    internal_search_title: string;
    /**
     * The description to use to display internal search results.
     */
    internal_search_description: string;
    /**
     * The keywords to use to optimize the internal search engine. Use very specific keywords or parts of text you want this content to rank for.
     */
    internal_search_keywords: string;
  };
  content?:
    | (
        | {
            richText?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            image: string | Media;
            /**
             * The alt text to use for the image.
             */
            alt: string;
            /**
             * The caption to use for the image.
             */
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image-block';
          }
        | {
            note: string;
            'note-type': 'suggestion' | 'note' | 'warning' | 'danger';
            id?: string | null;
            blockName?: string | null;
            blockType: 'note-block';
          }
        | {
            /**
             * The markdown table to use for the article.
             *                 Use the following format:
             *                 | Header 1 | Header 2 | Header 3 |
             *                 |----------|----------|----------|
             *                 | Cell 1   | Cell 2   | Cell 3   |
             *                 | Cell 4   | Cell 5   | Cell 6   |
             *                 | Cell 7   | Cell 8   | Cell 9   |
             *
             */
            'markdown-table': string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'markdown-table';
          }
        | {
            /**
             * The title to use for the related articles block.
             */
            'related-articles-title': string;
            'related-articles': (
              | {
                  relationTo: 'pguide';
                  value: string | Pguide;
                }
              | {
                  relationTo: 'guidelines';
                  value: string | Guideline;
                }
            )[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'related-articles-block';
          }
      )[]
    | null;
  'previous-next-navigation'?: {
    'previous-guide'?: (string | null) | Pguide;
    'next-guide'?: (string | null) | Pguide;
  };
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'guidelines';
        value: string | Guideline;
      } | null)
    | ({
        relationTo: 'pguide';
        value: string | Pguide;
      } | null)
    | ({
        relationTo: 'payload-kv';
        value: string | PayloadKv;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: string | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guidelines_select".
 */
export interface GuidelinesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  localeSummary?:
    | T
    | {
        locale?: T;
        countryISO?: T;
        dialingCode?: T;
        countryCode?: T;
      };
  regulatoryRequirements?:
    | T
    | {
        requirementsSelection?: T;
      };
  description?: T;
  localOperators?:
    | T
    | {
        operator?: T;
        mnc?: T;
        numericId?: T;
        alphaId?: T;
        shortCode?: T;
        comments?: T;
        id?: T;
      };
  features?:
    | T
    | {
        dedicatedShortcodes?: T;
        sharedShortcodes?: T;
        longnumbers?: T;
      };
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pguide_select".
 */
export interface PguideSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  meta_fields?:
    | T
    | {
        seo_title?: T;
        seo_description?: T;
        og_title?: T;
        og_description?: T;
        og_image?: T;
      };
  internal_search?:
    | T
    | {
        internal_search_title?: T;
        internal_search_description?: T;
        internal_search_keywords?: T;
      };
  content?:
    | T
    | {
        richText?:
          | T
          | {
              richText?: T;
              id?: T;
              blockName?: T;
            };
        'image-block'?:
          | T
          | {
              image?: T;
              alt?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        'note-block'?:
          | T
          | {
              note?: T;
              'note-type'?: T;
              id?: T;
              blockName?: T;
            };
        'markdown-table'?:
          | T
          | {
              'markdown-table'?: T;
              id?: T;
              blockName?: T;
            };
        'related-articles-block'?:
          | T
          | {
              'related-articles-title'?: T;
              'related-articles'?: T;
              id?: T;
              blockName?: T;
            };
      };
  'previous-next-navigation'?:
    | T
    | {
        'previous-guide'?: T;
        'next-guide'?: T;
      };
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}